version: '3'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_CREATE_TOPICS: "catz:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper

    cassandra:
        image: cassandra:latest
        container_name: cassandra
        ports:
            - "9042:9042"
        restart: always
        volumes:
            - ./cassandra_data:/var/lib/cassandra

    cassandra-load-schema:
        container_name: cassandra-load-schema
        image: cassandra:latest
        depends_on:
            - cassandra
        volumes:
            - ./src/main/resources/setup.cql:/setup.cql
        # The sleep trick is necessary as conditions in 'depends_on' are not supported in v3
        command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /setup.cql"

    catz-broker:
        image: c4catz/catz-broker:latest
        container_name: broker
        restart: on-failure # hack to start once Cassandra is up without bothering
                            # to healthcheck
        depends_on:
            - cassandra
            - kafka

    catz-app:
        image: c4catz/catz-app:latest
        container_name: cats
        stdin_open: true
        tty: true
        depends_on:
            - catz-broker